default:
  image: node:20
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline

build-job:
  stage: build
  image: node:20
  script:
    - npm run build
  artifacts:
    when: on_success
    expire_in: 1 week
    paths:
      - dist

test-job:
  stage: test
  script:
    - npm run lint
    - npm run format:check
    - npm run test
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)%/' # Adjust this regex to match your output
  artifacts:
    when: on_success
    expire_in: 1 week
    paths:
      - coverage/
    reports:
      junit: coverage/lcov.info
