default:
  image: node:20
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline

lint-job:
  stage: lint
  script: npm run lint

prettier-job:
 stage: format
 script: npm run format:check

build-job:
  stage: build
  image: node:20
  script:
    - npm run build
  artifacts:
    when: on_success
    expire_in: 1 week
    paths:
      - dist

test-job:
  stage: test
  script:
    - npm run test
